### ISSUE TITLE
Threshold for Significant Values

### ISSUE THREAD

**Issue by Rundon-svg** [moshi4/CafePlotter#2]
Hi moshi4,

Did the threshold set to 0.5, not 0.05 for significant counts?
This plotter has helped me a lot since cafe was updated to version 5. 
However, when I tried to export significant orthogroups IDs for next GO annotation, I found that the marked number on the significant tree was larger than the count exported directly from command line.
And I downloaded the example data (singlelambda.zip) and found the same thing.
: “Human” have 748 significant orthogroups (probablities less than 0.05 from Base_branch_probabilities.tab). And 863 are shown in the significant tree (Summary of significant expansion/contraction gene family results).

**Comment by moshi4** [comment]
Hi @Rundon-svg,

The threshold is correct at 0.05.

First of all, `summary_significant_gene_family.png` plot does not use the data from `Base_branch_probabilities.tab`.
I think there is a misunderstanding in the data interpretation.

`summary_significant_gene_family.png` is the result of a trial plot, but it seems to confuse users.
I don't think it is a necessary result, so I will remove it in the next release. Therefore, please ignore it.

**Comment by Rundon-svg** [comment]
Thank you for your help, moshi4. I appreciate your explanation and solution. I will try it out😊. If I have any more questions, I’ll be sure to ask. Thanks again! 🙏

**Comment by cfz1998** [comment]
> Hi @Rundon-svg,
> 
> The threshold is correct at 0.05.
> 
> First of all, `summary_significant_gene_family.png` plot does not use the data from `Base_branch_probabilities.tab`. I think there is a misunderstanding in the data interpretation.
> 
> `summary_significant_gene_family.png` is the result of a trial plot, but it seems to confuse users. I don't think it is a necessary result, so I will remove it in the next release. Therefore, please ignore it.

Hi! @moshi4 
How does the data form to draw `summary_significant_gene_family.png`？
I don't know the `Summary of significant expansion/contraction gene family result`.

Thank you for your reply!
-- CFD
