### ISSUE TITLE
Add time scale and pie chart

### ISSUE THREAD

**Issue by xiekunwhy** [moshi4/CafePlotter#6]
Hi,

Is it possible to add timescale and pie chart, like many papers do,

for example, figure 4 in https://academic.oup.com/gigascience/article/8/11/giz136/5628061?login=false
figure 6 in https://academic.oup.com/dnaresearch/article/25/3/245/4791394?login=false

Best,
Kun

**Comment by moshi4** [comment]
Hi @xiekunwhy,

CafePlotter does not have the functionality to plot timescale and pie charts. 
There are no plans to implement them in the future.
