### ISSUE TITLE
Is there a way to show only numbers of significantly expanded and contracted gene families on tree branches and nodes?

### ISSUE THREAD

**Issue by YuzhouGong** [moshi4/CafePlotter#7]
Hi Moshi4,
Thanks for your great tool to visualize the outputs of CAFE5. Because there were many gene families gone through expansion and contraction (like more than 5000) in my CAFE analysis, so I want to filter them to only show the number of significantly expanded/contracted ones on my tree, is that possible by using CAFE_plotter?
Thanks in advance!

**Comment by moshi4** [comment]
Hi @YuzhouGong,

CafePlotter only provides the functionality to plot the output results of CAFE5 on a phylogenetic tree in a simple and understandable way, and there is no option to plot customized results. I do not have much plan to add such functionality in the future.

**Comment by YuzhouGong** [comment]
Hi Moshi4,
Thank you for your quick reply!
