### ISSUE TITLE
Incomplete file generation

### ISSUE THREAD

**Issue by wjq1981** [moshi4/CafePlotter#8]
Hi, when I use v0.2.0, I found that not all the local files are generated after the program finishes running, and there is no “summary_significant_gene_family” generated, but I don't have these problems when I run v0.1.1.

**Comment by moshi4** [comment]
`summary_significant_gene_family.png` is removed in v0.2.0. See [v0.2.0 Change Log](https://github.com/moshi4/CafePlotter/releases/tag/v0.2.0) for details.

**Comment by wjq1981** [comment]
I'm not sure how the numerical mismatch described in question #2 arises. But I tested that the significant results in "Gamma_family_results.txt" are the same as the significant results in "summary_significant_gene_family".
